file=".env"
echo "VUE_APP_SERVER_URL=$VUE_APP_SERVER_URL" > $file
echo "VUE_APP_REAL_SERVER_URL=$VUE_APP_REAL_SERVER_URL" >> $file
echo "VUE_APP_GRAYLOG_SERVER_URL=$VUE_APP_GRAYLOG_SERVER_URL" >> $file
echo "VUE_APP_GRAYLOG_REAL_SERVER_URL=$VUE_APP_GRAYLOG_REAL_SERVER_URL" >> $file
echo "VUE_APP_GRAYLOG_USERNAME"=$VUE_APP_GRAYLOG_USERNAME >> $file
echo "VUE_APP_GRAYLOG_PASSWORD"=$VUE_APP_GRAYLOG_PASSWORD >> $file
cat $file