FROM centos:8.2.2004

WORKDIR /app

RUN curl -sL https://rpm.nodesource.com/setup_12.x --output addNodeRepo.sh
RUN sh addNodeRepo.sh
RUN yum install -y nodejs

COPY . .

RUN npm install
RUN npm install @vue/cli -g

#ENTRYPOINT ["sh", "docker_init.sh"]
#ENTRYPOINT ["npm", "run", "serve"]
CMD sh docker_init.sh ; npm run serve
